function [names] = canonicalNames()
	names = [
		"Stimulus (mA) for 50% max response",
		"Strength-duration time constant (ms)",
		"Rheobase (mA)",
		"Stimulus-response slope",
		"Peak response (mv)",
		"Resting I/V slope",
		"Minimum I/V slope",
		"Temperature ( C)",
		"RRP (ms)",
		"TEh(90-100ms)",
		"TEd(10-20ms)",
		"Superexcitability (%)",
		"Subexcitability (%)",
		"Age (years)",
		"Sex (M=1, F=2)",
		"Latency (ms)",
		"TEd(40-60ms)",
		"TEd(90-100ms)",
		"TEh(10-20ms)",
		"TEd(undershoot)",
		"TEh(overshoot)",
		"TEd(peak)",
		"S2 accommodation",
		"Accommodation half-time (ms)",
		"Hyperpol. I/V slope",
		"Refractoriness at 2.5ms (%)",
		"TEh(20-40ms)",
		"TEh(slope 101-140ms)",
		"Refractoriness at 2 ms (%)",
		"Superexcitability at 7 ms (%)",
		"Superexcitability at 5 ms (%)",
		"TEd20(peak)",
		"TEd40(Accom)",
		"TEd20(10-20ms)",
		"TEh20(10-20ms)",
	];
end
